/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.ApplicantDirectory;
import Model.Business;
import Model.InsurancePlans;
import Model.PlanDetail;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asequ
 */
public class CreateInsuranceJPanel extends javax.swing.JPanel {

    private Business business;
    DefaultTableModel viewTableModel;
    private PlanDetail plan;

    /**
     * Creates new form InsuranceJPanel
     */
    public CreateInsuranceJPanel() {
        initComponents();
    }

   
    CreateInsuranceJPanel(Business business) {
        initComponents();
        this.business = business;
        this.viewTableModel = (DefaultTableModel) insuranceTable.getModel();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtPlanId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        insuranceTable = new javax.swing.JTable();
        viewInsuranceDetails = new javax.swing.JButton();
        addInsuranceBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtCostPerMonth = new javax.swing.JTextField();
        txtPlanName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel5.setText("CREATE INSURANCE PLAN");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 550, 20));
        add(txtPlanId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 120, 30));

        jLabel14.setText("PLAN NAME");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 20));

        jLabel6.setText("COST PER MONTH");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 20));

        insuranceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLAN ID", "PLAN NAME", "Cost per Month", "Cost per Annum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(insuranceTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 360, 290));

        viewInsuranceDetails.setText("VIEW DETAILS");
        viewInsuranceDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInsuranceDetailsActionPerformed(evt);
            }
        });
        add(viewInsuranceDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 140, 30));

        addInsuranceBtn.setText("CREATE INSURANCE PLAN");
        addInsuranceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInsuranceBtnActionPerformed(evt);
            }
        });
        add(addInsuranceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 40));

        jLabel15.setText("PLAN ID");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 20));
        add(txtCostPerMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 120, 30));
        add(txtPlanName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void addInsuranceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInsuranceBtnActionPerformed
        // TODO add your handling code here:
        String planId = txtPlanId.getText();
        String planName = txtPlanName.getText();
        String costPerMonth = txtCostPerMonth.getText();
        String costPerAnnum = String.valueOf(Double.valueOf(costPerMonth) * 12);
        PlanDetail insurance = this.business.getInsurancePlans().createPlans(Integer.valueOf(planId), planName, Double.valueOf(costPerMonth),Double.valueOf(costPerAnnum) );
        JOptionPane.showMessageDialog(null, "Added Insurance");
    }//GEN-LAST:event_addInsuranceBtnActionPerformed

    private void viewInsuranceDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInsuranceDetailsActionPerformed
        // TODO add your handling code here:
        displayObservation();
    }//GEN-LAST:event_viewInsuranceDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addInsuranceBtn;
    private javax.swing.JTable insuranceTable;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCostPerMonth;
    private javax.swing.JTextField txtPlanId;
    private javax.swing.JTextField txtPlanName;
    private javax.swing.JButton viewInsuranceDetails;
    // End of variables declaration//GEN-END:variables

    private void displayObservation() {
           InsurancePlans plan = this.business.getInsurancePlans();
        if(plan.getInsurancePlanList().size() > 0){
            viewTableModel.setRowCount(0);
            for( PlanDetail o: plan.getInsurancePlanList())
            {
//                System.out.println(o.getObservationId());
                Object row[]= new Object[4];
                row[0] = o.getPlanId();
                row[1] = o.getPlanName();
                row[2] = o.getCostPerMonth();
                row[3] = o.getCostPerAnnum();
                //this.viewTableModel.
                viewTableModel.addRow(row);
            }
        }
        else{
            System.out.println("Empty List");
        }
    }
}
