/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author asequ
 */
public class PetJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PetJPanel
     */
    public PetJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        addVaccineBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel5.setText("UPDATE PET DETAILS");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 550, 20));

        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setForeground(new java.awt.Color(204, 204, 204));
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 120, 30));

        jLabel14.setText("APPLICANT ID");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 20));

        addVaccineBtn.setText("UPDATE PET DETAILS");
        addVaccineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccineBtnActionPerformed(evt);
            }
        });
        add(addVaccineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pet Name", "Pet Age", "Gender", "Breed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 270, 290));

        jButton1.setText("VIEW DETAILS");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 140, 30));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 120, 30));

        jLabel6.setText("PET NAME");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, 20));

        jLabel8.setText("PET AGE");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 70, 20));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 120, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 120, 30));

        jLabel7.setText("GENDER");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 70, 20));

        jLabel9.setText("BREED");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 70, 20));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void addVaccineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccineBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVaccineBtnActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVaccineBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
