/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.ChefDetails;

/**
 *
 * @author asequ
 */
public class ReadJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReadJPanel
     */
    private ChefDetails chefDetails;
    public ReadJPanel() {
        initComponents();
    }
    ReadJPanel(ChefDetails chefDetails) {
        initComponents();
        this.chefDetails = new ChefDetails();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chefLastNamejLabel1 = new javax.swing.JLabel();
        recipeTitlejLabel1 = new javax.swing.JLabel();
        noOfIngredientsjLabel1 = new javax.swing.JLabel();
        glutenFreeLabel1 = new javax.swing.JLabel();
        recipeDetailsLabel = new javax.swing.JLabel();
        recipePictureLabel1 = new javax.swing.JLabel();
        descriptionLabel1 = new javax.swing.JLabel();
        noOfServing2 = new javax.swing.JTextField();
        userName2 = new javax.swing.JTextField();
        noOfIngredients2 = new javax.swing.JTextField();
        chefFirstName2 = new javax.swing.JTextField();
        contactDetailLabel1 = new javax.swing.JLabel();
        noOfServingjLabel = new javax.swing.JLabel();
        noOfServingjLabel1 = new javax.swing.JLabel();
        chefLastName2 = new javax.swing.JTextField();
        emailId1 = new javax.swing.JTextField();
        sliderTextField3 = new javax.swing.JTextField();
        emailIdLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextArea1 = new javax.swing.JTextArea();
        categoryOfFoodLabel1 = new javax.swing.JLabel();
        recipeTitle2 = new javax.swing.JTextField();
        phoneNumberLabel1 = new javax.swing.JLabel();
        userNamejLabel1 = new javax.swing.JLabel();
        glutenFreeLabel3 = new javax.swing.JLabel();
        noOfServing1 = new javax.swing.JTextField();
        difficultyLevel = new javax.swing.JLabel();
        updateLabel = new javax.swing.JLabel();
        chefFirstNamejLabel1 = new javax.swing.JLabel();
        phoneNumber1 = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        imageBorderLabel1 = new javax.swing.JLabel();
        noOfIngredients3 = new javax.swing.JTextField();
        sliderTextField2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chefLastNamejLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        chefLastNamejLabel1.setText("Chef's Last Name");
        add(chefLastNamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        recipeTitlejLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        recipeTitlejLabel1.setText("Recipe Title");
        add(recipeTitlejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        noOfIngredientsjLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        noOfIngredientsjLabel1.setText("No. of Ingredients");
        add(noOfIngredientsjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        glutenFreeLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        glutenFreeLabel1.setText("is gluten free?");
        add(glutenFreeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 80, 20));

        recipeDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recipeDetailsLabel.setText("Recipe Details");
        add(recipeDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 30));

        recipePictureLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        recipePictureLabel1.setText("Recipe Picture");
        add(recipePictureLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        descriptionLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        descriptionLabel1.setText("Description");
        add(descriptionLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 80, 20));

        noOfServing2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfServing2ActionPerformed(evt);
            }
        });
        add(noOfServing2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, 30));

        userName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName2ActionPerformed(evt);
            }
        });
        add(userName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, 30));

        noOfIngredients2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfIngredients2ActionPerformed(evt);
            }
        });
        add(noOfIngredients2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 70, 30));

        chefFirstName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chefFirstName2ActionPerformed(evt);
            }
        });
        add(chefFirstName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, 30));

        contactDetailLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactDetailLabel1.setText("Contact Details");
        add(contactDetailLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 110, 30));

        noOfServingjLabel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        noOfServingjLabel.setText("No. of servings");
        add(noOfServingjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        noOfServingjLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        noOfServingjLabel1.setText("No. of servings");
        add(noOfServingjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        chefLastName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chefLastName2ActionPerformed(evt);
            }
        });
        add(chefLastName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 70, 30));

        emailId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailId1ActionPerformed(evt);
            }
        });
        add(emailId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 140, 20));

        sliderTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sliderTextField3ActionPerformed(evt);
            }
        });
        add(sliderTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 50, -1));

        emailIdLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        emailIdLabel1.setText("Email Id");
        add(emailIdLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 50, 20));

        descriptionTextArea1.setColumns(20);
        descriptionTextArea1.setRows(5);
        jScrollPane2.setViewportView(descriptionTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 180, 60));

        categoryOfFoodLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        categoryOfFoodLabel1.setText("Category of food");
        add(categoryOfFoodLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, 20));

        recipeTitle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeTitle2ActionPerformed(evt);
            }
        });
        add(recipeTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 70, 30));

        phoneNumberLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        phoneNumberLabel1.setText("Phone");
        add(phoneNumberLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 40, 10));

        userNamejLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        userNamejLabel1.setText("Username");
        add(userNamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        glutenFreeLabel3.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        glutenFreeLabel3.setText("Difficult level");
        add(glutenFreeLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 80, 20));

        noOfServing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfServing1ActionPerformed(evt);
            }
        });
        add(noOfServing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, 30));

        difficultyLevel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        difficultyLevel.setText("Difficult level");
        add(difficultyLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 80, 20));

        updateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateLabel.setText("DISPLAY");
        add(updateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 70, 30));

        chefFirstNamejLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        chefFirstNamejLabel1.setText("Chef's First Name");
        add(chefFirstNamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        phoneNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumber1ActionPerformed(evt);
            }
        });
        add(phoneNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 140, 20));

        updateButton.setText("UPDATE");
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 80, 30));

        imageBorderLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        imageBorderLabel1.setForeground(new java.awt.Color(255, 255, 255));
        imageBorderLabel1.setText("Text Displayed here");
        imageBorderLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(imageBorderLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 170, 110));

        noOfIngredients3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfIngredients3ActionPerformed(evt);
            }
        });
        add(noOfIngredients3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 70, 30));

        sliderTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sliderTextField2ActionPerformed(evt);
            }
        });
        add(sliderTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 50, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void noOfServing2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfServing2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfServing2ActionPerformed

    private void userName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userName2ActionPerformed

    private void noOfIngredients2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfIngredients2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfIngredients2ActionPerformed

    private void chefFirstName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chefFirstName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chefFirstName2ActionPerformed

    private void chefLastName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chefLastName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chefLastName2ActionPerformed

    private void emailId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailId1ActionPerformed

    private void sliderTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sliderTextField3ActionPerformed
        // TODO add your handling code here:
        //int sliderNumber = descriptionSlider1.getValue();
        //sliderTextField3.setText(String.valueOf(sliderNumber));
    }//GEN-LAST:event_sliderTextField3ActionPerformed

    private void recipeTitle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeTitle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recipeTitle2ActionPerformed

    private void noOfServing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfServing1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfServing1ActionPerformed

    private void phoneNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumber1ActionPerformed

    private void noOfIngredients3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfIngredients3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfIngredients3ActionPerformed

    private void sliderTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sliderTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sliderTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryOfFoodLabel1;
    private javax.swing.JTextField chefFirstName2;
    private javax.swing.JLabel chefFirstNamejLabel1;
    private javax.swing.JTextField chefLastName2;
    private javax.swing.JLabel chefLastNamejLabel1;
    private javax.swing.JLabel contactDetailLabel1;
    private javax.swing.JLabel descriptionLabel1;
    private javax.swing.JTextArea descriptionTextArea1;
    private javax.swing.JLabel difficultyLevel;
    private javax.swing.JTextField emailId1;
    private javax.swing.JLabel emailIdLabel1;
    private javax.swing.JLabel glutenFreeLabel1;
    private javax.swing.JLabel glutenFreeLabel3;
    private javax.swing.JLabel imageBorderLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField noOfIngredients2;
    private javax.swing.JTextField noOfIngredients3;
    private javax.swing.JLabel noOfIngredientsjLabel1;
    private javax.swing.JTextField noOfServing1;
    private javax.swing.JTextField noOfServing2;
    private javax.swing.JLabel noOfServingjLabel;
    private javax.swing.JLabel noOfServingjLabel1;
    private javax.swing.JTextField phoneNumber1;
    private javax.swing.JLabel phoneNumberLabel1;
    private javax.swing.JLabel recipeDetailsLabel;
    private javax.swing.JLabel recipePictureLabel1;
    private javax.swing.JTextField recipeTitle2;
    private javax.swing.JLabel recipeTitlejLabel1;
    private javax.swing.JTextField sliderTextField2;
    private javax.swing.JTextField sliderTextField3;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel updateLabel;
    private javax.swing.JTextField userName2;
    private javax.swing.JLabel userNamejLabel1;
    // End of variables declaration//GEN-END:variables
}
