/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Applicant;
import Model.ApplicantDirectory;
import Model.Business;
import Model.InsurancePlans;
import Model.PetDetails;
import Model.PlanDetail;
import Model.VaccineDetails;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asequ
 */
public class UpdateApplicantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApplicantJPanel
     */
    private Business business;
    private Applicant applicantAccount;
    private PetDetails pet;
    DefaultTableModel tableModel;
     private int count=0;
    
    public UpdateApplicantJPanel() {
        initComponents();
        this.business = business;
        this.applicantAccount = applicantAccount;
    }

    

    UpdateApplicantJPanel(Business business, Applicant applicantAccount) {
        this.setVisible(true);
        initComponents();
        this.business = business;
        this.applicantAccount = applicantAccount;
        //pet = this.applicantAccount.getPet();
        this.tableModel = (DefaultTableModel)viewTableAppl.getModel();
        displayInsuranceDp();
    }

 

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPetName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPetAge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboPetGender = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtBreed = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addApplicantBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        comboInsurancePlan = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        txtApplicantId = new javax.swing.JTextField();
        txtPetType = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewTableAppl = new javax.swing.JTable();
        viewApplBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel1.setText("UPDATE APPLICANT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        jLabel2.setText("FIRST NAME");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, 20));
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 120, 30));

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, 30));

        jLabel3.setText("DATE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 70, 20));

        jLabel4.setText("LAST NAME");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 70, 20));

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel5.setText("DISPLAY APPLICANT AND PET DETAILS");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 550, 20));
        add(txtPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 120, 30));

        jLabel6.setText("PET NAME");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 70, 20));
        add(txtPetAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 120, 30));

        jLabel7.setText("GENDER");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 70, 20));

        jLabel8.setText("PET AGE");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 70, 20));

        comboPetGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        add(comboPetGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 120, 30));

        jLabel9.setText("BREED");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 70, 20));
        add(txtBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 120, 30));

        jLabel10.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel10.setText("UPDATE PET DETAILS");
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 550, 20));

        addApplicantBtn.setText("ADD APPLICANT");
        addApplicantBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addApplicantBtnActionPerformed(evt);
            }
        });
        add(addApplicantBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 140, 30));

        jLabel14.setText("INSURANCE PLANS");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 20));

        comboInsurancePlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInsurancePlanActionPerformed(evt);
            }
        });
        add(comboInsurancePlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 440, 40));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 180, 30));

        jLabel15.setText("APPLICANT ID");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 70, 20));
        add(txtApplicantId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, 30));
        add(txtPetType, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 120, 30));

        jLabel16.setText("PET TYPE");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 70, 20));

        viewTableAppl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Applicant ID", "First Name", "Last Name", "Date", "Pet Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewTableAppl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 550, 150));

        viewApplBtn.setText("VIEW ");
        viewApplBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewApplBtnActionPerformed(evt);
            }
        });
        add(viewApplBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 700, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void addApplicantBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addApplicantBtnActionPerformed
        // TODO add your handling code here:
        String applicantId = txtApplicantId.getText();
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        Date dateValue = jDateChooser1.getDate();
        String petName = txtPetName.getText();
        String petAge = txtPetAge.getText();
        String petType = txtPetType.getText();
        String gender = (String) comboPetGender.getSelectedItem();
        String breed = txtBreed.getText();
        String insurancePlan = (String)comboInsurancePlan.getSelectedItem();
       // System.out.println("Added date details " +dateValue);
        //PetDetails pet = this.applicantAccount.getPet();
      
        //pet.setApplicantId(Integer.valueOf(applicantId));
        //applicantAccount.setPet(pet);
        
        
        
        //this.applicantAccount = this.business.getApplicantDirectory().createApplicant(Integer.valueOf(applicantId), firstName, lastName, dateValue, petName,  Integer.valueOf(petAge),  gender,  petType,  breed,insurancePlan,petId);
       //System.out.println("pet Name  " + pet.getPetName());
        //this.applicantAccount.addPet(pet);
        JOptionPane.showMessageDialog(null, "Added Applicant");
            
         
    }//GEN-LAST:event_addApplicantBtnActionPerformed

    private void comboInsurancePlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInsurancePlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboInsurancePlanActionPerformed

    private void viewApplBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewApplBtnActionPerformed
        // TODO add your handling code here:
        displayView();
        //count++;
    }//GEN-LAST:event_viewApplBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addApplicantBtn;
    private javax.swing.JComboBox<String> comboInsurancePlan;
    private javax.swing.JComboBox<String> comboPetGender;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApplicantId;
    private javax.swing.JTextField txtBreed;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPetAge;
    private javax.swing.JTextField txtPetName;
    private javax.swing.JTextField txtPetType;
    private javax.swing.JButton viewApplBtn;
    private javax.swing.JTable viewTableAppl;
    // End of variables declaration//GEN-END:variables

    private void displayInsuranceDp() {
         comboInsurancePlan.removeAllItems();
        
        for(PlanDetail d : this.business.getInsurancePlans().getInsurancePlanList()) {
            comboInsurancePlan.addItem("PLAN ID: " + d.getPlanId() + "PLAN NAME: " + d.getPlanName() + "COST PER MONTH: " + d.getCostPerMonth() + "COST PER ANNUM: " + d.getCostPerAnnum());       
        }
    }

    private void displayView() {
//        int varCount = count;
//        if(count == 0) 
//        {
//            varCount = 0;
//        }
//        else 
//        {
//            varCount = count - 1;
//        }
           tableModel.setRowCount(0);
        for (Applicant o: this.business.getApplicantDirectory().getApplicantList()){
            //Applicant pet = o;
            
            //PetDetails petS =  o.getPet();
            Object[] row = new Object[6];
            row[0] = o.getApplicationID();
            System.out.println("Inside view method " + o.getApplicationID());
            row[1] = o.getOwnerFirstName();
            row[2] = o.getOwnerLastName();
            row[3] = String.valueOf(o.getApplicationDate());
            row[4] = o.getPet().getPetName();
            row[5] = o.getPet().getGender();
            
           
            //System.out.println("" + o.getPet());
            
            
            
            //System.out.println("Inside pet view method " + o.getPet());
//            row[5] = o.getPet().getPetAge();
//            row[6] = o.getPet().getGender();
//            row[7] = o.getPet().getBreed();
//            row[8] = o.getPet().getInsuranceDetails();
          
            //row[5] = o.getPet().getPetType();
            tableModel.addRow(row);
        } //To change body of generated methods, choose Tools | Templates.
        
    
    }
}
