/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.ChefDetails;
import Model.ContactInformation;
import Model.Recipe;
import Validation.ValidationClass;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Andrea Joyce Sequeira
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    private ChefDetails chefDetails;
    private ValidationClass val;
    public UpdateJPanel() {
        initComponents();
    }
    UpdateJPanel(ChefDetails chefDetails) throws IOException  {
        initComponents();
        this.chefDetails = chefDetails;
        displayChefDetailsList();
        val = new ValidationClass();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactDetailLabel1 = new javax.swing.JLabel();
        chefFirstName1 = new javax.swing.JTextField();
        chefFirstNamejLabel1 = new javax.swing.JLabel();
        chefLastNamejLabel1 = new javax.swing.JLabel();
        chefLastName1 = new javax.swing.JTextField();
        userName1 = new javax.swing.JTextField();
        userNamejLabel1 = new javax.swing.JLabel();
        updateLabel = new javax.swing.JLabel();
        noOfServing = new javax.swing.JTextField();
        recipeTitle1 = new javax.swing.JTextField();
        recipeTitlejLabel1 = new javax.swing.JLabel();
        noOfServingjLabel = new javax.swing.JLabel();
        noOfServingjLabel1 = new javax.swing.JLabel();
        noOfServing1 = new javax.swing.JTextField();
        noOfIngredientsjLabel1 = new javax.swing.JLabel();
        noOfIngredients1 = new javax.swing.JTextField();
        descriptionLabel1 = new javax.swing.JLabel();
        glutenFree1 = new javax.swing.JComboBox<>();
        glutenFreeLabel1 = new javax.swing.JLabel();
        descriptionSlider1 = new javax.swing.JSlider();
        difficultyLevel = new javax.swing.JLabel();
        glutenFreeLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextArea1 = new javax.swing.JTextArea();
        categoryOfFoodLabel1 = new javax.swing.JLabel();
        recipePictureLabel1 = new javax.swing.JLabel();
        recipeDetailsLabel = new javax.swing.JLabel();
        phoneNumber1 = new javax.swing.JTextField();
        emailId1 = new javax.swing.JTextField();
        emailIdLabel1 = new javax.swing.JLabel();
        phoneNumberLabel1 = new javax.swing.JLabel();
        browsePictureButton1 = new javax.swing.JButton();
        sliderTextField1 = new javax.swing.JTextField();
        categoryOfFood1 = new javax.swing.JComboBox<>();
        imageBorderLabel1 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contactDetailLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactDetailLabel1.setText("Update Contact Details");
        add(contactDetailLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 190, 30));

        chefFirstName1.setBackground(new java.awt.Color(204, 204, 204));
        chefFirstName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chefFirstName1ActionPerformed(evt);
            }
        });
        add(chefFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, 30));

        chefFirstNamejLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        chefFirstNamejLabel1.setText("Chef's First Name");
        add(chefFirstNamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        chefLastNamejLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        chefLastNamejLabel1.setText("Chef's Last Name");
        add(chefLastNamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        chefLastName1.setBackground(new java.awt.Color(204, 204, 204));
        chefLastName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chefLastName1ActionPerformed(evt);
            }
        });
        add(chefLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 70, 30));

        userName1.setBackground(new java.awt.Color(204, 204, 204));
        userName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName1ActionPerformed(evt);
            }
        });
        add(userName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 70, 30));

        userNamejLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        userNamejLabel1.setText("Username");
        add(userNamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        updateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateLabel.setText("UPDATE");
        add(updateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 80, 20));

        noOfServing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfServingActionPerformed(evt);
            }
        });
        add(noOfServing, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, 30));

        recipeTitle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipeTitle1ActionPerformed(evt);
            }
        });
        add(recipeTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 70, 30));

        recipeTitlejLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        recipeTitlejLabel1.setText("Recipe Title");
        add(recipeTitlejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        noOfServingjLabel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        noOfServingjLabel.setText("No. of servings");
        add(noOfServingjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        noOfServingjLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        noOfServingjLabel1.setText("No. of servings");
        add(noOfServingjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        noOfServing1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfServing1ActionPerformed(evt);
            }
        });
        add(noOfServing1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, 30));

        noOfIngredientsjLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        noOfIngredientsjLabel1.setText("No. of Ingredients");
        add(noOfIngredientsjLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        noOfIngredients1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfIngredients1ActionPerformed(evt);
            }
        });
        add(noOfIngredients1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 70, 30));

        descriptionLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        descriptionLabel1.setText("Description");
        add(descriptionLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 80, 20));

        glutenFree1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        add(glutenFree1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 70, 30));

        glutenFreeLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        glutenFreeLabel1.setText("is gluten free?");
        add(glutenFreeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 80, 20));

        descriptionSlider1.setMaximum(5);
        descriptionSlider1.setMinimum(1);
        descriptionSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                descriptionSlider1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                descriptionSlider1MouseMoved(evt);
            }
        });
        descriptionSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descriptionSlider1MouseClicked(evt);
            }
        });
        add(descriptionSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 140, -1));

        difficultyLevel.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        difficultyLevel.setText("Difficult level");
        add(difficultyLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 80, 20));

        glutenFreeLabel3.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        glutenFreeLabel3.setText("Difficult level");
        add(glutenFreeLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 80, 20));

        descriptionTextArea1.setColumns(20);
        descriptionTextArea1.setRows(5);
        jScrollPane2.setViewportView(descriptionTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 180, 110));

        categoryOfFoodLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        categoryOfFoodLabel1.setText("Category of food");
        add(categoryOfFoodLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, 20));

        recipePictureLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        recipePictureLabel1.setText("Recipe Picture");
        add(recipePictureLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        recipeDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recipeDetailsLabel.setText("Recipe Details");
        add(recipeDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 30));

        phoneNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumber1ActionPerformed(evt);
            }
        });
        add(phoneNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 120, 30));

        emailId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailId1ActionPerformed(evt);
            }
        });
        add(emailId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 120, 30));

        emailIdLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        emailIdLabel1.setText("Email Id");
        add(emailIdLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 50, 20));

        phoneNumberLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        phoneNumberLabel1.setText("Phone");
        add(phoneNumberLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 40, 10));

        browsePictureButton1.setText("BROWSE");
        browsePictureButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsePictureButton1ActionPerformed(evt);
            }
        });
        add(browsePictureButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, -1));

        sliderTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sliderTextField1ActionPerformed(evt);
            }
        });
        add(sliderTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 40, 30));

        categoryOfFood1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian", "Italian", "Chinese", "Japanese" }));
        add(categoryOfFood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        imageBorderLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        imageBorderLabel1.setForeground(new java.awt.Color(255, 255, 255));
        imageBorderLabel1.setText("      Upload your image ");
        imageBorderLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(imageBorderLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 170, 120));

        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void chefFirstName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chefFirstName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chefFirstName1ActionPerformed

    private void chefLastName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chefLastName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chefLastName1ActionPerformed

    private void userName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userName1ActionPerformed

    private void noOfServingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfServingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfServingActionPerformed

    private void recipeTitle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipeTitle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recipeTitle1ActionPerformed

    private void noOfServing1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfServing1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfServing1ActionPerformed

    private void noOfIngredients1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfIngredients1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfIngredients1ActionPerformed

    private void descriptionSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionSlider1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionSlider1MouseDragged

    private void descriptionSlider1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionSlider1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionSlider1MouseMoved

    private void phoneNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumber1ActionPerformed

    private void emailId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailId1ActionPerformed

    private void browsePictureButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsePictureButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        if(showOpenDialogue == JFileChooser.APPROVE_OPTION)
        {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            System.out.println(selectedImagePath);
            JOptionPane.showMessageDialog(null,selectedImagePath );
            //Store the filePath in recipe picture variable
            Recipe recipe = this.chefDetails.getRecipe();
            recipe.setRecipePicture(selectedImagePath);
            System.out.println("displaypath:" + recipe.getRecipePicture());
            ImageIcon ii = new ImageIcon(selectedImagePath);
            Image image = ii.getImage().getScaledInstance(imageBorderLabel1.getWidth(),imageBorderLabel1.getHeight(), Image.SCALE_SMOOTH);
            imageBorderLabel1.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_browsePictureButton1ActionPerformed

    private void sliderTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sliderTextField1ActionPerformed
        // TODO add your handling code here:
        double sliderNumber = descriptionSlider1.getValue();
        sliderTextField1.setText(String.valueOf(sliderNumber));
         

    }//GEN-LAST:event_sliderTextField1ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
       Recipe recipe = this.chefDetails.getRecipe();
            Boolean glutenFreeValue = true;
        if (glutenFree1.getSelectedItem() == "Yes") 
        { 
             glutenFreeValue = true; 
        } else 
        {  
            glutenFreeValue = false; 
        }
         //validation check
        boolean flag = false;
        String recipePictureValue = recipe.getRecipePicture();
        if (val.validateEmail(emailId1.getText())) {
            flag = true;
            JOptionPane.showMessageDialog(null, "Email format: someone@email.com", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            System.out.println("Email Validation check passed");
        }


        if (val.nullCheck(emailId1.getText())   || val.nullCheck(recipeTitle1.getText()) || val.nullCheck(noOfServing.getText()) || val.nullCheck(noOfIngredients1.getText()) || val.nullCheck(String.valueOf(categoryOfFood1.getSelectedItem())) || val.nullCheck(String.valueOf(glutenFreeValue)) || val.nullCheck(descriptionTextArea1.getText()) || val.nullCheck(descriptionTextArea1.getText()) || val.nullCheck(recipePictureValue)) {
            flag = true;
            JOptionPane.showMessageDialog(null, "Null value is not allowed!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            System.out.println("Null check passed");
        }
        
        if (val.silderCheck(String.valueOf(sliderTextField1.getText()))) {
            flag = true;
            JOptionPane.showMessageDialog(null, "Difficulty level should be between 1 to 5", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            System.out.println("Difficulty level check passed");
        }

        if (val.phoneNumberCheck(phoneNumber1.getText())) {
            flag = true;
            JOptionPane.showMessageDialog(null, "Phone Number should be 10 Characters", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            System.out.println("Phone Number check passed");
        }
        
        
        recipe.setRecipeTitle(recipeTitle1.getText());
        recipe.setNoOfServing(Integer.valueOf(noOfServing.getText()));
        recipe.setNoOfIngredients(Integer.valueOf(noOfIngredients1.getText()));
        recipe.setCategoryOfFood(String.valueOf(categoryOfFood1.getSelectedItem()));
       
   
        recipe.setIsGlutenFree(Boolean.valueOf(glutenFreeValue));
        recipe.setDifficultyLevel(Double.valueOf(sliderTextField1.getText()));
        recipe.setDescription(descriptionTextArea1.getText());

        ContactInformation contact = this.chefDetails.getContact();
        contact.setEmailId(emailId1.getText());
        contact.setPhoneNumber(Long.valueOf(phoneNumber1.getText()));
        
       

        if (flag == false) {
            JOptionPane.showMessageDialog(null, "UPDATED SUCCESSFULLY");
        } else {
            System.out.println("Validation check failed");
        }
        
        
       
    }//GEN-LAST:event_updateButtonActionPerformed

    private void descriptionSlider1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descriptionSlider1MouseClicked
        // TODO add your handling code here:
             double sliderNumber = descriptionSlider1.getValue();
        sliderTextField1.setText(String.valueOf(sliderNumber));
    }//GEN-LAST:event_descriptionSlider1MouseClicked
  public void displayChefDetailsList() throws IOException {
        // Set the values of Chef Details
        chefFirstName1.setText(this.chefDetails.getChefFirstName());
        System.out.println("Updated image " + this.chefDetails.getChefFirstName());
        chefLastName1.setText(this.chefDetails.getChefLastName());
        userName1.setText(this.chefDetails.getUserName());
        
        Recipe recipe = this.chefDetails.getRecipe();
        recipeTitle1.setText(recipe.getRecipeTitle());
        noOfServing.setText(String.valueOf(recipe.getNoOfServing()));
        noOfIngredients1.setText(String.valueOf(recipe.getNoOfIngredients()));
        categoryOfFood1.setSelectedItem(recipe.getCategoryOfFood());
        glutenFree1.setSelectedItem(recipe.getIsGlutenFree());
        sliderTextField1.setText(String.valueOf(recipe.getDifficultyLevel()));
        descriptionTextArea1.setText(recipe.getDescription());
        String imagePathValue = recipe.getRecipePicture();
        System.out.println("Updated image " + imagePathValue);
       
      
        ImageIcon ii = new ImageIcon(imagePathValue);
        Image image = ii.getImage();
        imageBorderLabel1.setIcon(new ImageIcon(image));
       
        ContactInformation contact = this.chefDetails.getContact();
        emailId1.setText(contact.getEmailId());
        phoneNumber1.setText(String.valueOf(contact.getPhoneNumber()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browsePictureButton1;
    private javax.swing.JComboBox<String> categoryOfFood1;
    private javax.swing.JLabel categoryOfFoodLabel1;
    private javax.swing.JTextField chefFirstName1;
    private javax.swing.JLabel chefFirstNamejLabel1;
    private javax.swing.JTextField chefLastName1;
    private javax.swing.JLabel chefLastNamejLabel1;
    private javax.swing.JLabel contactDetailLabel1;
    private javax.swing.JLabel descriptionLabel1;
    private javax.swing.JSlider descriptionSlider1;
    private javax.swing.JTextArea descriptionTextArea1;
    private javax.swing.JLabel difficultyLevel;
    private javax.swing.JTextField emailId1;
    private javax.swing.JLabel emailIdLabel1;
    private javax.swing.JComboBox<String> glutenFree1;
    private javax.swing.JLabel glutenFreeLabel1;
    private javax.swing.JLabel glutenFreeLabel3;
    private javax.swing.JLabel imageBorderLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField noOfIngredients1;
    private javax.swing.JLabel noOfIngredientsjLabel1;
    private javax.swing.JTextField noOfServing;
    private javax.swing.JTextField noOfServing1;
    private javax.swing.JLabel noOfServingjLabel;
    private javax.swing.JLabel noOfServingjLabel1;
    private javax.swing.JTextField phoneNumber1;
    private javax.swing.JLabel phoneNumberLabel1;
    private javax.swing.JLabel recipeDetailsLabel;
    private javax.swing.JLabel recipePictureLabel1;
    private javax.swing.JTextField recipeTitle1;
    private javax.swing.JLabel recipeTitlejLabel1;
    private javax.swing.JTextField sliderTextField1;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel updateLabel;
    private javax.swing.JTextField userName1;
    private javax.swing.JLabel userNamejLabel1;
    // End of variables declaration//GEN-END:variables
}
