/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.LibrarianPanel;

import UI.SystemAdminPanel.*;
import Model.Employee.Employee;
import Model.Employee.EmployeeDirectory;
import Model.Library.Library;
import Model.Material.Book;
import Model.Material.BookCollection;
import Model.Rental.Rent;
import Model.Role.LibrarianRole;
import Model.Role.Role;
import Model.Role.SystemAdminRole;
import Model.system.ApplicationSystem;
import Model.system.Branch;
import Model.system.UserAccount;
import Model.system.UserAccountDirectory;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asequ
 */
public class AddBookJPanel extends javax.swing.JPanel {

    private ApplicationSystem applicationsystem;
    private Branch branch;
    private UserAccount useraccount;
    DefaultTableModel viewTableModel;
    /** Creates new form CreateBranchJPanel */

    
    public AddBookJPanel() {
        initComponents();

    }

    public AddBookJPanel(ApplicationSystem applicationsystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.viewTableModel = (DefaultTableModel) tableBookTable.getModel();  
        this.applicationsystem = applicationsystem;
        this.branch = branch;
        this.useraccount = useraccount;
        displayBook();
        //displayLibraryDp();
//        displayBookDetails();
//        displayBook();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLanguages = new javax.swing.JTextField();
        btnBookAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBookTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBookPages = new javax.swing.JTextField();
        txtAuthorName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtGenreName = new javax.swing.JTextField();
        comboBoxRentDuration = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRentPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        comboBoxAvailable = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboBoxTyoeOfBinding = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 204, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("BOOK NAME");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 40));

        txtLanguages.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLanguagesFocusLost(evt);
            }
        });
        add(txtLanguages, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, 30));

        btnBookAdd.setText("ADD");
        btnBookAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAddActionPerformed(evt);
            }
        });
        add(btnBookAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, 130, 30));

        tableBookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOK NAME", "No. of Pages", "Languages", "Author", "Genre", "Type of Binding", "Date", "Available", "Rent Price", "Rent Duration", "Serial Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBookTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 920, 380));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("LANGUAGES");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 40));

        txtBookName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBookNameFocusLost(evt);
            }
        });
        txtBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookNameActionPerformed(evt);
            }
        });
        add(txtBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("NO OF PAGES");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("AUTHOR");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 40));

        txtBookPages.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBookPagesFocusLost(evt);
            }
        });
        txtBookPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookPagesActionPerformed(evt);
            }
        });
        add(txtBookPages, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 30));

        txtAuthorName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAuthorNameFocusLost(evt);
            }
        });
        add(txtAuthorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("GENRE");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("TYPE OF BINDING");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 130, 40));

        txtGenreName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGenreNameFocusLost(evt);
            }
        });
        add(txtGenreName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 160, 30));

        comboBoxRentDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "one week", "two week", "three week" }));
        add(comboBoxRentDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 160, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel5.setText("RENTAL INFORMATION");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 475, 950, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("RENT PRICE");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 130, 40));

        txtRentPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRentPriceFocusLost(evt);
            }
        });
        add(txtRentPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("REGISTERED DATE");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 130, 40));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("Available ?");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 130, 40));

        comboBoxAvailable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        add(comboBoxAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("RENT DURATION");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 130, 40));

        comboBoxTyoeOfBinding.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hardcover", "Wire", "Saddle" }));
        add(comboBoxTyoeOfBinding, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 160, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel12.setText("ADD BOOK TO LIBRARY");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 280, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("SERIAL NUMBER");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 130, 40));

        txtSerialNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSerialNumberFocusLost(evt);
            }
        });
        add(txtSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAddActionPerformed
        // TODO add your handling code here:
//        String branchName = txtAge.getText();
//        String libraryName = "PublicLibrary-" + branchName;
//        String buildingNum = txtBuildNumber.getText();
//        this.branch = this.applicationsystem.createBranch(branchName,libraryName,Integer.valueOf(buildingNum));
//        JOptionPane.showMessageDialog(null, "Added branch");
//        displayBranch();
          //Add Book Details
          String bookName = txtBookName.getText();
          String noOfPages = txtBookPages.getText();
          String languages = txtLanguages.getText();
          String authorName = txtAuthorName.getText();
          String genreName = txtGenreName.getText();
          String typeOfBinding = (String) comboBoxTyoeOfBinding.getSelectedItem();
          Date dateValue = jDateChooser1.getDate();
          String isAvailable =  (String) comboBoxAvailable.getSelectedItem();
          Boolean isAvailableValue;
          if(isAvailable == "Yes")
          {
              isAvailableValue = true;
          }
          else {
              isAvailableValue = false;
          }
          
          //Rent information
          String rentPrice = txtRentPrice.getText();
          String rentDuration = (String) comboBoxRentDuration.getSelectedItem();
          String serialNumber = txtSerialNumber.getText();
          
          
          Library lib = this.branch.getLib();
          Book book = new Book();
          BookCollection bookcollection = lib.getBooklist();
          
          book.setMaterialName(bookName);
          book.setNoOfPages(Integer.valueOf(noOfPages));
          book.setLanguages(languages);
          book.setAuthorName(authorName);
          book.setGenre(genreName);
          book.setTypeOfBinding(typeOfBinding);
          book.setRegisteredDate(dateValue);
          book.setIsAvailableFlag(isAvailableValue);
          book.setLocation(this.useraccount.getAccessTo());
          Rent rt = book.getRt();
          rt.setRentDuration(rentDuration);
          rt.setRentPrice(Double.valueOf(rentPrice));
          rt.setSerialNumber(Long.valueOf(serialNumber));
          rt.setStatus("Available");
          
          //adding author and genre to the list
          lib.getAuthorCompleteList().addAuthor(authorName);
          lib.getGenreCompleteList().addGenre(genreName);
          
          book.setRt(rt);
          bookcollection.getBooklistCollection().add(book);
          
          lib.setBooklist(bookcollection);
          
          //Fetching branch name
//          String branchName = fetchBranchName();
          
         
          
          this.applicationsystem.AddBookToBranch(this.branch.getName(), lib);

          JOptionPane.showMessageDialog(null, "Book Added");

          
          displayBook();
          
          
       
          
          
    }//GEN-LAST:event_btnBookAddActionPerformed

    private void txtLanguagesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLanguagesFocusLost
        // TODO add your handling code here:
//        String branchName = txtAge.getText();
//        txtLibName.setText("PublicLibrary-"+branchName);
    }//GEN-LAST:event_txtLanguagesFocusLost

    private void txtBookNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookNameFocusLost

    private void txtBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookNameActionPerformed

    private void txtBookPagesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookPagesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookPagesFocusLost

    private void txtAuthorNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAuthorNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorNameFocusLost

    private void txtGenreNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGenreNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenreNameFocusLost

    private void txtBookPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookPagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookPagesActionPerformed

    private void txtRentPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRentPriceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRentPriceFocusLost

    private void txtSerialNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSerialNumberFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookAdd;
    private javax.swing.JComboBox<String> comboBoxAvailable;
    private javax.swing.JComboBox<String> comboBoxRentDuration;
    private javax.swing.JComboBox<String> comboBoxTyoeOfBinding;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBookTable;
    private javax.swing.JTextField txtAuthorName;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtBookPages;
    private javax.swing.JTextField txtGenreName;
    private javax.swing.JTextField txtLanguages;
    private javax.swing.JTextField txtRentPrice;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables

public String fetchBranchName()
    {
        String BranchName = "";
        String userAccountValue = this.useraccount.getAccountId();      
        ArrayList<Branch> br = this.applicationsystem.getBranches();
        int fetchNumber = 0;
        for(int i=0;i< br.size(); i++){
            String emp = br.get(i).getLib().getEmployeelist().getEmployeelist().get(i).getPersonId();
            if(emp.equals(userAccountValue) ){
                fetchNumber = i;
                break;  
            }
        }
        BranchName = br.get(fetchNumber).getName();
        System.out.println("BRANCH NAME PRINTING "+BranchName);
        return BranchName;
    }

    private void displayBook(){
        viewTableModel.setRowCount(0);
//        ArrayList<Branch> br = this.applicationsystem.getBranches();
       
          
          Library lib = this.branch.getLib();
          ArrayList<Book> bookcollection = lib.getBooklist().getBooklistCollection();
          
        
//        String branchNameFunc = fetchBranchName();
          for(int i =0;i< bookcollection.size();i++ ){
               Object row[] = new Object[11];
               if(bookcollection.get(i).getLocation().equals(useraccount.getAccessTo()))
               {
                     row[0] = bookcollection.get(i).getMaterialName();
                     row[1] = bookcollection.get(i).getNoOfPages();
                     row[2] = bookcollection.get(i).getLanguages();
                     row[3] = bookcollection.get(i).getAuthorName();
                     row[4] = bookcollection.get(i).getGenre();
                     row[5] = bookcollection.get(i).getTypeOfBinding();
                     row[6] = String.valueOf(bookcollection.get(i).getRegisteredDate());
                     row[7] = bookcollection.get(i).getIsAvailableFlag();
                     row[8] = bookcollection.get(i).getRt().getRentPrice();
                     row[9] = bookcollection.get(i).getRt().getRentDuration();
                     row[10] = bookcollection.get(i).getRt().getSerialNumber();
                    
                    viewTableModel.addRow(row);
               }
                  
             
              }    
          }
    }
    
 
     


