/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.SystemAdminPanel;

import Model.Customer.Customer;
import Model.Customer.CustomerDirectory;
import Model.Employee.Employee;
import Model.Employee.EmployeeDirectory;
import Model.Role.CustomerRole;
import Model.Role.Role;
import Model.Role.SystemAdminRole;
import Model.system.ApplicationSystem;
import Model.system.Branch;
import Model.system.UserAccount;
import Model.system.UserAccountDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrea Joyce Sequeira
 */
public class CustomerJPanel extends javax.swing.JPanel {

    private ApplicationSystem applicationsystem;
    private Branch branch;
    private UserAccount useraccount;
    DefaultTableModel viewTableModel;
    /** Creates new form CreateBranchJPanel */

    
    public CustomerJPanel() {
        initComponents();
    }

    public CustomerJPanel(ApplicationSystem applicationsystem, Branch branch, UserAccount useraccount) {
        initComponents();
        this.viewTableModel = (DefaultTableModel) tableCustomer.getModel();  
        this.applicationsystem = applicationsystem;
        this.branch = branch;
        this.useraccount = useraccount;
        displayCustomer();
        
//        displayLibraryDp();
//        displayBranchManager();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLibSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustomer = new javax.swing.JTable();
        txtCustomerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerAge = new javax.swing.JTextField();
        txtAge1 = new javax.swing.JTextField();
        txtCustomerUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCustomerPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("CUSTOMER NAME");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 170, 40));

        btnLibSubmit.setText("ADD");
        btnLibSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibSubmitActionPerformed(evt);
            }
        });
        add(btnLibSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 80, 30));

        tableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "AGE", "USERNAME", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCustomer);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 580, 370));

        txtCustomerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerNameFocusLost(evt);
            }
        });
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("CUSTOMER AGE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, 40));

        txtCustomerAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerAgeFocusLost(evt);
            }
        });
        add(txtCustomerAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, 30));

        txtAge1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAge1FocusLost(evt);
            }
        });
        add(txtAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, 30));

        txtCustomerUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerUsernameFocusLost(evt);
            }
        });
        add(txtCustomerUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 160, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("USERNAME");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 130, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("PASSWORD");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 130, 40));

        txtCustomerPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCustomerPasswordFocusLost(evt);
            }
        });
        add(txtCustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 160, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLibSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibSubmitActionPerformed
        // TODO add your handling code here:
//        String branchName = txtAge.getText();
//        String libraryName = "PublicLibrary-" + branchName;
//        String buildingNum = txtBuildNumber.getText();
//        this.branch = this.applicationsystem.createBranch(branchName,libraryName,Integer.valueOf(buildingNum));
//        JOptionPane.showMessageDialog(null, "Added branch");
//        displayBranch();
          String custName = txtCustomerName.getText();
          String custAge = txtCustomerAge.getText();
          String userName = txtCustomerUsername.getText();
          String passWord = txtCustomerPassword.getText();
            
        UserAccountDirectory ua = this.applicationsystem.getTopLevelUserAccountDirectory();
        if(ua.accountExists(userName)) {
            JOptionPane.showMessageDialog(null, "Sorry  credentials are taken");
            
        }
        else {
//            UserAccount user = this.applicationsystem.getTopLevelUserAccountDirectory().createUserAccount(userName, passWord , new SystemAdminRole());
            //this.branch.getLib().getEmployeelist().createEmployeeAccount(user.getAccountId(), libName, Integer.valueOf(libAge), "branch manager", Integer.valueOf(experience),libraryName);
            UserAccount user = this.applicationsystem.getTopLevelUserAccountDirectory().createUserAccount(userName, passWord , new CustomerRole(),"ALL");
            this.applicationsystem.getCustomerList().addCustomer(custName,Integer.valueOf(custAge),user.getAccountId());
            JOptionPane.showMessageDialog(null, "Customer has been added");
            displayCustomer();
        }
          
          
    }//GEN-LAST:event_btnLibSubmitActionPerformed

    private void txtCustomerNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameFocusLost

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtCustomerAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerAgeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerAgeFocusLost

    private void txtAge1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAge1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAge1FocusLost

    private void txtCustomerUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerUsernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerUsernameFocusLost

    private void txtCustomerPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerPasswordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerPasswordFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLibSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCustomer;
    private javax.swing.JTextField txtAge1;
    private javax.swing.JTextField txtCustomerAge;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPassword;
    private javax.swing.JTextField txtCustomerUsername;
    // End of variables declaration//GEN-END:variables

    private void displayCustomer() {
        ArrayList<Customer> cust = this.applicationsystem.getCustomerList().getCustomerlist();

        viewTableModel.setRowCount(0);
        
        for(int i=0;i<cust.size();i++){
//            UserAccount u = this.applicationsystem.getTopLevelUserAccountDirectory().findbyId(emp.getPersonId());
             Object row[] = new Object[6];
             UserAccount u = this.applicationsystem.getTopLevelUserAccountDirectory().findbyId(cust.get(i).getCustomerId());
              row[0] = cust.get(i).getCustomerName();
              row[1] = cust.get(i).getCustomerAge();
              row[2] = u.getUsername();
              row[3] = u.getPassword();
              viewTableModel.addRow(row);
        }

                        
    }

   

  
}
